spring.application.name=meta-lead-backend
spring.datasource.url=jdbc:mysql://localhost:3306/meta_leads
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=root7788
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
meta.verify-token=${META_VERIFY_TOKEN}